name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Add information to the tracker
        uses: fjogeleit/http-request-action@master
        env:
          RELEASE_DESCRIPTION: "((${{ github.server_url }}/${{github.repository}}/releases/tag/${{ env.RELEASE_VERSION }} Release ${{ env.RELEASE_VERSION }})) has been made.\nRelease created by: ${{github.actor}}\n\nChangelog:\n ${{steps.Changelog.outputs.changelog}}\n\n Tests successfully done. ((${{ github.server_url }}/${{github.repository}}/runs/${{ github.run_id }}?check_suite_focus=true#step:5:8 see log))"
        with:
          url: "https://api.tracker.yandex.net/v2/issues/"
          method: "POST"
          timeout: "30000"
          customHeaders: '{"Authorization": "OAuth ${{ secrets.TRACKER_TOKEN }}", "X-Org-ID": "${{ secrets.TRACKER_ORG_ID }}"}'
          data: '{
            "queue": {"key": "TMP"},
            "summary": "Release ${{ env.RELEASE_VERSION }} ",
            "description": ${{ toJson(env.RELEASE_DESCRIPTION) }}
          }'
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '^16.11.1'
      - run: npm i
      - run: npm test